language: android
sudo: required
jdk: oraclejdk8

env:
  global:
    - GRADLE_OPTS=-Xmx512m
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - android-15
    - android-19
    - android-21
    - android-28
    - build-tools-28.0.3
    - extra-android-m2repository
    - platform-tools
    - tools
  licenses:
    - 'android-sdk-license-.+'

script:
  - ./gradlew assemble anvil:check --stacktrace
